//
//  Goal.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Goal: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _goalId: String?
    var _amountSaved: NSNumber?
    var _deadline: String?
    var _lastSaved: String?
    var _name: String?
    var _targetAmount: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "spendonyoursavings-mobilehub-2000920463-Goal"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_goalId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_goalId" : "goalId",
               "_amountSaved" : "amountSaved",
               "_deadline" : "deadline",
               "_lastSaved" : "lastSaved",
               "_name" : "name",
               "_targetAmount" : "targetAmount",
        ]
    }
}
