# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spend_to_save' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spend_to_save
  pod 'AWSCore', '~> 2.7.0'
  pod 'AWSAppSync', '~> 2.6.24'
  pod 'AWSMobileClient', '~> 2.7.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.7.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.7.0'   # Optional dependency required to use drop-in UI
  
  target 'spend_to_saveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'spend_to_saveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
